name: Build

on:
  push:
    branches:    
      - main

jobs:
  build_wheels:
    name: Build ${{ matrix.package }} wheels on ${{ matrix.os }}, for Python ${{ matrix.python_build_version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ "macOS-12" ]
        python_build_version: [ "cp311" ]
        package: [ "grpcio", "grpcio-tools" ]

    steps:
      # Used to host cibuildwheel
      - name: Set up Python
        uses: actions/setup-python@v4      
      - name: Download latest ${{ matrix.package }} stable tarball
        run: |
          pip download --no-binary ${{ matrix.package }} ${{ matrix.package }}==1.48.1
          tar xf *.tar.gz
          
      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.9.0

      - name: Build wheels
        run: |
          cd ${{ matrix.package }}-*/
          python -m cibuildwheel --output-dir ../wheelhouse
        env:
          CIBW_ARCHS_MACOS: "arm64"
          CIBW_TEST_SKIP: "*_arm64"
          CIBW_BUILD: "${{ matrix.python_build_version }}-macosx_arm64"
          CIBW_BUILD_FRONTEND: pip
          CIBW_ENVIRONMENT_MACOS: "GRPC_PYTHON_BUILD_WITH_CYTHON=1"
          CIBW_BEFORE_BUILD: "pip install Cython; if [[ -f requirements.txt ]]; then pip install -r requirements.txt; fi"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "grpcio 1.48.1"
          tag_name: v1.48.1
          files: ./wheelhouse/*.whl
          body: "Apple Silicon built binaries for the grpcio 1.48.1 Python library."
